[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day_04 = "6VpH7jvQCXNVW1oozrSVh1EJDdC9RgZYC5D8YRrqwkcv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
